config/routes.rb
Rails.application.routes.draw do
  resources :treatments
  resources :tooth_statuses
  resources :tooths
  resources :odontograms
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :tooth_status
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: %i[ show edit update destroy ]

  # GET /treatments or /treatments.json
  def index
    @treatments = Treatment.all
  end

  # GET /treatments/1 or /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments or /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to treatment_url(@treatment), notice: "Treatment was successfully created." }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1 or /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to treatment_url(@treatment), notice: "Treatment was successfully updated." }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1 or /treatments/1.json
  def destroy
    @treatment.destroy

    respond_to do |format|
      format.html { redirect_to treatments_url, notice: "Treatment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def treatment_params
      params.require(:treatment).permit(:treatment_type, :start_date, :end_date, :duration, :tooth_status_id)
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= form_with(model: treatment) do |form| %>
  <% if treatment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
        <% treatment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :treatment_type, style: "display: block" %>
    <%= form.number_field :treatment_type %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :tooth_status_id, style: "display: block" %>
    <%= form.text_field :tooth_status_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/treatments/_treatment.html.erb
<div id="<%= dom_id treatment %>">
  <p>
    <strong>Treatment type:</strong>
    <%= treatment.treatment_type %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= treatment.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= treatment.end_date %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= treatment.duration %>
  </p>

  <p>
    <strong>Tooth status:</strong>
    <%= treatment.tooth_status_id %>
  </p>

</div>

app/views/treatments/edit.html.erb
<h1>Editing treatment</h1>

<%= render "form", treatment: @treatment %>

<br>

<div>
  <%= link_to "Show this treatment", @treatment %> |
  <%= link_to "Back to treatments", treatments_path %>
</div>

app/views/treatments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Treatments</h1>

<div id="treatments">
  <% @treatments.each do |treatment| %>
    <%= render treatment %>
    <p>
      <%= link_to "Show this treatment", treatment %>
    </p>
  <% end %>
</div>

<%= link_to "New treatment", new_treatment_path %>

app/views/treatments/new.html.erb
<h1>New treatment</h1>

<%= render "form", treatment: @treatment %>

<br>

<div>
  <%= link_to "Back to treatments", treatments_path %>
</div>

app/views/treatments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @treatment %>

<div>
  <%= link_to "Edit this treatment", edit_treatment_path(@treatment) %> |
  <%= link_to "Back to treatments", treatments_path %>

  <%= button_to "Destroy this treatment", @treatment, method: :delete %>
</div>