config/routes.rb
Rails.application.routes.draw do
  resources :treatments
  resources :tooth_statuses
  resources :tooths
  resources :odontograms
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tooth.rb
class Tooth < ApplicationRecord
  belongs_to :odontogram
end

app/controllers/tooths_controller.rb
class ToothsController < ApplicationController
  before_action :set_tooth, only: %i[ show edit update destroy ]

  # GET /tooths or /tooths.json
  def index
    @tooths = Tooth.all
  end

  # GET /tooths/1 or /tooths/1.json
  def show
  end

  # GET /tooths/new
  def new
    @tooth = Tooth.new
  end

  # GET /tooths/1/edit
  def edit
  end

  # POST /tooths or /tooths.json
  def create
    @tooth = Tooth.new(tooth_params)

    respond_to do |format|
      if @tooth.save
        format.html { redirect_to tooth_url(@tooth), notice: "Tooth was successfully created." }
        format.json { render :show, status: :created, location: @tooth }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tooth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tooths/1 or /tooths/1.json
  def update
    respond_to do |format|
      if @tooth.update(tooth_params)
        format.html { redirect_to tooth_url(@tooth), notice: "Tooth was successfully updated." }
        format.json { render :show, status: :ok, location: @tooth }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tooth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tooths/1 or /tooths/1.json
  def destroy
    @tooth.destroy

    respond_to do |format|
      format.html { redirect_to tooths_url, notice: "Tooth was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tooth
      @tooth = Tooth.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tooth_params
      params.require(:tooth).permit(:position, :tooth_type, :number, :odontogram_id)
    end
end

app/helpers/tooths_helper.rb
module ToothsHelper
end

app/views/tooths/_form.html.erb
<%= form_with(model: tooth) do |form| %>
  <% if tooth.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tooth.errors.count, "error") %> prohibited this tooth from being saved:</h2>

      <ul>
        <% tooth.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :tooth_type, style: "display: block" %>
    <%= form.number_field :tooth_type %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :odontogram_id, style: "display: block" %>
    <%= form.text_field :odontogram_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tooths/_tooth.html.erb
<div id="<%= dom_id tooth %>">
  <p>
    <strong>Position:</strong>
    <%= tooth.position %>
  </p>

  <p>
    <strong>Tooth type:</strong>
    <%= tooth.tooth_type %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= tooth.number %>
  </p>

  <p>
    <strong>Odontogram:</strong>
    <%= tooth.odontogram_id %>
  </p>

</div>

app/views/tooths/edit.html.erb
<h1>Editing tooth</h1>

<%= render "form", tooth: @tooth %>

<br>

<div>
  <%= link_to "Show this tooth", @tooth %> |
  <%= link_to "Back to tooths", tooths_path %>
</div>

app/views/tooths/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tooths</h1>

<div id="tooths">
  <% @tooths.each do |tooth| %>
    <%= render tooth %>
    <p>
      <%= link_to "Show this tooth", tooth %>
    </p>
  <% end %>
</div>

<%= link_to "New tooth", new_tooth_path %>

app/views/tooths/new.html.erb
<h1>New tooth</h1>

<%= render "form", tooth: @tooth %>

<br>

<div>
  <%= link_to "Back to tooths", tooths_path %>
</div>

app/views/tooths/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tooth %>

<div>
  <%= link_to "Edit this tooth", edit_tooth_path(@tooth) %> |
  <%= link_to "Back to tooths", tooths_path %>

  <%= button_to "Destroy this tooth", @tooth, method: :delete %>
</div>