config/routes.rb
Rails.application.routes.draw do
  resources :treatments
  resources :tooth_statuses
  resources :tooths
  resources :odontograms
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/tooth_statuses_controller.rb
class ToothStatusesController < ApplicationController
  before_action :set_tooth_status, only: %i[ show edit update destroy ]

  # GET /tooth_statuses or /tooth_statuses.json
  def index
    @tooth_statuses = ToothStatus.all
  end

  # GET /tooth_statuses/1 or /tooth_statuses/1.json
  def show
  end

  # GET /tooth_statuses/new
  def new
    @tooth_status = ToothStatus.new
  end

  # GET /tooth_statuses/1/edit
  def edit
  end

  # POST /tooth_statuses or /tooth_statuses.json
  def create
    @tooth_status = ToothStatus.new(tooth_status_params)

    respond_to do |format|
      if @tooth_status.save
        format.html { redirect_to tooth_status_url(@tooth_status), notice: "Tooth status was successfully created." }
        format.json { render :show, status: :created, location: @tooth_status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tooth_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tooth_statuses/1 or /tooth_statuses/1.json
  def update
    respond_to do |format|
      if @tooth_status.update(tooth_status_params)
        format.html { redirect_to tooth_status_url(@tooth_status), notice: "Tooth status was successfully updated." }
        format.json { render :show, status: :ok, location: @tooth_status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tooth_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tooth_statuses/1 or /tooth_statuses/1.json
  def destroy
    @tooth_status.destroy

    respond_to do |format|
      format.html { redirect_to tooth_statuses_url, notice: "Tooth status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tooth_status
      @tooth_status = ToothStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tooth_status_params
      params.require(:tooth_status).permit(:current_treatment, :treatment_history, :observations, :tooth_id)
    end
end

app/helpers/tooth_statuses_helper.rb
module ToothStatusesHelper
end

app/views/tooth_statuses/_form.html.erb
<%= form_with(model: tooth_status) do |form| %>
  <% if tooth_status.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tooth_status.errors.count, "error") %> prohibited this tooth_status from being saved:</h2>

      <ul>
        <% tooth_status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :current_treatment, style: "display: block" %>
    <%= form.check_box :current_treatment %>
  </div>

  <div>
    <%= form.label :treatment_history, style: "display: block" %>
    <%= form.text_area :treatment_history %>
  </div>

  <div>
    <%= form.label :observations, style: "display: block" %>
    <%= form.text_area :observations %>
  </div>

  <div>
    <%= form.label :tooth_id, style: "display: block" %>
    <%= form.text_field :tooth_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tooth_statuses/_tooth_status.html.erb
<div id="<%= dom_id tooth_status %>">
  <p>
    <strong>Current treatment:</strong>
    <%= tooth_status.current_treatment %>
  </p>

  <p>
    <strong>Treatment history:</strong>
    <%= tooth_status.treatment_history %>
  </p>

  <p>
    <strong>Observations:</strong>
    <%= tooth_status.observations %>
  </p>

  <p>
    <strong>Tooth:</strong>
    <%= tooth_status.tooth_id %>
  </p>

</div>

app/views/tooth_statuses/edit.html.erb
<h1>Editing tooth status</h1>

<%= render "form", tooth_status: @tooth_status %>

<br>

<div>
  <%= link_to "Show this tooth status", @tooth_status %> |
  <%= link_to "Back to tooth statuses", tooth_statuses_path %>
</div>

app/views/tooth_statuses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tooth statuses</h1>

<div id="tooth_statuses">
  <% @tooth_statuses.each do |tooth_status| %>
    <%= render tooth_status %>
    <p>
      <%= link_to "Show this tooth status", tooth_status %>
    </p>
  <% end %>
</div>

<%= link_to "New tooth status", new_tooth_status_path %>

app/views/tooth_statuses/new.html.erb
<h1>New tooth status</h1>

<%= render "form", tooth_status: @tooth_status %>

<br>

<div>
  <%= link_to "Back to tooth statuses", tooth_statuses_path %>
</div>

app/views/tooth_statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tooth_status %>

<div>
  <%= link_to "Edit this tooth status", edit_tooth_status_path(@tooth_status) %> |
  <%= link_to "Back to tooth statuses", tooth_statuses_path %>

  <%= button_to "Destroy this tooth status", @tooth_status, method: :delete %>
</div>