config/routes.rb
Rails.application.routes.draw do
  resources :treatments
  resources :tooth_statuses
  resources :tooths
  resources :odontograms
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/odontogram.rb
class Odontogram < ApplicationRecord
  belongs_to :patient
end

app/controllers/odontograms_controller.rb
class OdontogramsController < ApplicationController
  before_action :set_odontogram, only: %i[ show edit update destroy ]

  # GET /odontograms or /odontograms.json
  def index
    @odontograms = Odontogram.all
  end

  # GET /odontograms/1 or /odontograms/1.json
  def show
  end

  # GET /odontograms/new
  def new
    @odontogram = Odontogram.new
  end

  # GET /odontograms/1/edit
  def edit
  end

  # POST /odontograms or /odontograms.json
  def create
    @odontogram = Odontogram.new(odontogram_params)

    respond_to do |format|
      if @odontogram.save
        format.html { redirect_to odontogram_url(@odontogram), notice: "Odontogram was successfully created." }
        format.json { render :show, status: :created, location: @odontogram }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @odontogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /odontograms/1 or /odontograms/1.json
  def update
    respond_to do |format|
      if @odontogram.update(odontogram_params)
        format.html { redirect_to odontogram_url(@odontogram), notice: "Odontogram was successfully updated." }
        format.json { render :show, status: :ok, location: @odontogram }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @odontogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /odontograms/1 or /odontograms/1.json
  def destroy
    @odontogram.destroy

    respond_to do |format|
      format.html { redirect_to odontograms_url, notice: "Odontogram was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_odontogram
      @odontogram = Odontogram.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def odontogram_params
      params.require(:odontogram).permit(:patient_id, :exam_date, :exam_type)
    end
end

app/helpers/odontograms_helper.rb
module OdontogramsHelper
end

app/views/odontograms/_form.html.erb
<%= form_with(model: odontogram) do |form| %>
  <% if odontogram.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(odontogram.errors.count, "error") %> prohibited this odontogram from being saved:</h2>

      <ul>
        <% odontogram.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.text_field :patient_id %>
  </div>

  <div>
    <%= form.label :exam_date, style: "display: block" %>
    <%= form.date_field :exam_date %>
  </div>

  <div>
    <%= form.label :exam_type, style: "display: block" %>
    <%= form.text_field :exam_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/odontograms/_odontogram.html.erb
<div id="<%= dom_id odontogram %>">
  <p>
    <strong>Patient:</strong>
    <%= odontogram.patient_id %>
  </p>

  <p>
    <strong>Exam date:</strong>
    <%= odontogram.exam_date %>
  </p>

  <p>
    <strong>Exam type:</strong>
    <%= odontogram.exam_type %>
  </p>

</div>

app/views/odontograms/edit.html.erb
<h1>Editing odontogram</h1>

<%= render "form", odontogram: @odontogram %>

<br>

<div>
  <%= link_to "Show this odontogram", @odontogram %> |
  <%= link_to "Back to odontograms", odontograms_path %>
</div>

app/views/odontograms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Odontograms</h1>

<div id="odontograms">
  <% @odontograms.each do |odontogram| %>
    <%= render odontogram %>
    <p>
      <%= link_to "Show this odontogram", odontogram %>
    </p>
  <% end %>
</div>

<%= link_to "New odontogram", new_odontogram_path %>

app/views/odontograms/new.html.erb
<h1>New odontogram</h1>

<%= render "form", odontogram: @odontogram %>

<br>

<div>
  <%= link_to "Back to odontograms", odontograms_path %>
</div>

app/views/odontograms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @odontogram %>

<div>
  <%= link_to "Edit this odontogram", edit_odontogram_path(@odontogram) %> |
  <%= link_to "Back to odontograms", odontograms_path %>

  <%= button_to "Destroy this odontogram", @odontogram, method: :delete %>
</div>